### ISSUE TITLE
'Serial2' was not declared in this scope

### ISSUE THREAD

**Issue by a85531647** [oymotion/gForceSDKCXX#1]
I have already include the library as the instruction says, but when I run the example program, it has this error: 'Serial2' was not declared in this scope. I want to know how to fix this.

**Comment by micheldevicq** [comment]
I have the same issue, so same question

**Comment by micheldevicq** [comment]
It seems if I select the board Arduino Mega it does work 
I'm not sure this is because I installed the driver, I'm not a software expert

**Comment by micheldevicq** [comment]
https://www.arduino.cc/reference/en/language/functions/communication/serial/

It seems the Mega has a serial 2 but the Arduino uno not, so you can change the serial 2 to nothing, to compile through?

**Comment by XavierCao** [comment]
如果你使用的是Arduino UNO这样的只有一个串口的设备，可以自己再创建一个软串口，类似这样：
![image](https://user-images.githubusercontent.com/34497803/61038651-f5f56980-a3ff-11e9-9f46-2b9a10d0939d.png)

**Comment by BigBro2014** [comment]
Yes, the issue for Arduino SDK is fixed. Thanks litelte and micheldevic.
