### ISSUE TITLE
我编译时出现了错误

### ISSUE THREAD

**Issue by XavierCao** [oymotion/gForceSDKCXX#2]
我是使用Arduino UNO来运行这个示例程序的。我首先创建了一个软串口，编译通过，但是又遇到了另外一个问题，如下：
![image](https://user-images.githubusercontent.com/34497803/61038954-7f0ca080-a400-11e9-8296-04704ea39ec5.png)
前面我增添软串口的代码，应该没什么问题。
![image](https://user-images.githubusercontent.com/34497803/61039050-a5cad700-a400-11e9-8235-4cce29de558e.png)
请求帮助。

**Comment by BigBro2014** [comment]
Try GFC_GetgForceData(...)?
