### ISSUE TITLE
Units for raw EMG data

### ISSUE THREAD

**Issue by Andrey1994** [oymotion/gForceSDKCXX#4]
Hi,

How to convert raw EMG values to microvolts(uV)?

**Comment by Andrey1994** [comment]
Also looking at these samples I dont understand who to parse this data. I've set 
```
ds->setEMGRawDataConfig (500,                     // sample rate
            (DeviceSetting::EMGRowDataChannels) (0x00FF), // channel 0~7
            128,                                          // data length
            12,                                           // adc resolution
            [this] (ResponseResult result) {
                std::string res =
                    (result == ResponseResult::RREST_SUCCESS) ? ("sucess") : ("failed");
                bIsEMGConfigured = (result == ResponseResult::RREST_SUCCESS) ? (true) : (false);
                this->logger->info ("setEMGRawDataConfig result: {}", res);
            });
```
And in callback I receive 128 bytes, who to parse these bytes to get per channel uV values?

**Comment by Andrey1994** [comment]
I use pooling mode and configured period to 1ms, so it should not be an issue I guess
```
void threadFunc ()
{
    GF_UINT32 period = 1; // ms
    while (!bShouldStopThread)
    {
        GF_RET_CODE retCode = pHub->run (period);
    }
}
```

**Comment by Andrey1994** [comment]
And I have the same question for Accel and Gyroscope. How to convert these values to commonly used units?

**Comment by BigBro2014** [comment]
Hi Andrey,
255 in 8bit means 3.2V/gains, while 4095 in 12bit mode mean 3.2V/gains. Gains should be 1250.
Read out of gyroscope is in q15 format(4 bytes long), whose value devided by 65535.0f will result in real value of gyro(in º/s unit).
The accel has the same q15 format, you may get the real acceleration value in m/s^2 by devide it with 65535.0f.

**Comment by BigBro2014** [comment]
Hi Andrey,
255 in 8bit means 1.25V/gains, while 4095 in 12bit mode means 1.25V/gains. Gains should be 1200.
Read out of gyroscope is in q15 format(4 bytes long), whose value devided by 65535.0f will result in real value of gyro(in º/s unit).
The accel has the same q15 format, you may get the real acceleration value in m/s^2 by devide it with 65535.0f.

**Comment by BigBro2014** [comment]
0 means -1.25V/gains, 127 in 8bit resolution means 0V.
